# TechHelp Support Bot – Unterstützungsmöglichkeiten / Ways to support
# Diese Datei zeigt auf GitHub einen "Sponsor"-Button. / This file shows a "Sponsor" button on GitHub.

buy_me_a_coffee: techhelp.support
custom:
  - "https://buymeacoffee.com/techhelp.support"
  - "https://bot.techhelp-support.de/"
