blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/Techhelp-Support/Techhelp-Support-Bot/discussions
    about: Für allgemeine Fragen und Ideen. / For general questions and ideas.
  - name: 🛟 Support & Hilfe / Support & Help
    url: https://bot.techhelp-support.de/support/
    about: Direkter Support vom Team. / Direct support from the team.
  - name: 🌐 Website
    url: https://bot.techhelp-support.de/
    about: Alle Infos zum Bot. / All info about the bot.
  - name: 📰 News & Updates
    url: https://bot.techhelp-support.de/techhelp-support-news-2/
    about: Neue Funktionen und Ankündigungen. / New features and announcements.
